version: 2.1

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - telegram/notify:
          parse_mode: "Markdown"
          message: "BUILD PACKAGE - $CIRCLE_PROJECT_REPONAME - << pipeline.git.branch >> - START"
      - node/install:
          install-yarn: true
          node-version: "16"
      - run:
          command: npm config set '//npm.pkg.github.com/:_authToken' "${NPM_TOKEN}"
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: npx semantic-release
          name: publish package
      - telegram-orb/status:
          success_only: true
          success_message: "✅ BUILD PACKAGE - $CIRCLE_PROJECT_REPONAME - << pipeline.git.branch >> - SUCCESS"
      - telegram-orb/status:
          fail_only: true
          failure_message: "❌ BUILD PACKAGE - $CIRCLE_PROJECT_REPONAME - << pipeline.git.branch >> - FAILURE"

orbs:
  node: circleci/node@4.0.0
  telegram: woltsu/telegram@0.0.9
  telegram-orb: uniqueck/telegram-orb@0.0.1

workflows:
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
          context: periodica-press-github-packages
