name: CI

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: install yarn
        run: npm i -g yarn

      - name: bootstrap
        run: yarn

      - name: config package registry
        run: npm config set '//npm.pkg.github.com/:_authToken' "${GH_TOKEN}"

      - name: publish
        run: npx semantic-release
